# **NumPy**

Lists s Numpy

* Numpy is faster when compared
to lists it is bacause it stores less data in when storing any item .



*   No type checking for eery entry
*  Continuous memory




In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
b= np.array([[1,4,4,5,654,43,3,3,3],[34,34,4,34,5,67,34,3,87]])
b

array([[  1,   4,   4,   5, 654,  43,   3,   3,   3],
       [ 34,  34,   4,  34,   5,  67,  34,   3,  87]])

**Get Dimension**

In [ ]:
#a.ndim

b.ndim

2

In [ ]:
b.shape #Tuple of array dimensions.

(2, 9)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize #Length of one array element in bytes.

8

In [ ]:
a.size #Number of elements in the array.

4

**Modification**

In [ ]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

In [ ]:
print(arr[1,6])

17


In [ ]:
arr[0,:] # specific row

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[:,4] # specific filter

array([ 5, 15])

In [ ]:
  arr[0,1:6:3] #[startindex:endindex:stepsize]

array([2, 5])

In [ ]:
arr[ :,2] = [1,2]
print(arr)

[[ 1  2  1  4  5  6  7  8  9 10]
 [11 12  2 14 15 16 17 18 19 20]]


In [ ]:
barr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(barr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
barr[1,1,1]

np.int64(11)

**Initialize**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a,4)

array([4, 4, 4, 4])

In [ ]:
np.random.rand(a.shape[0]) # random floats

array([0.76025639, 0.50961414, 0.83528271, 0.67632627])

In [ ]:
np.random.randint(5,8888,size=(2,2) )

array([[5603,  798],
       [6380, 4524]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
arr1 = np.array([[1,2,3,4,5]])
r1 = np.repeat(arr1,3, axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
output = np.ones((5,5))
#print(output)

z = np.zeros((3,3))
z[1,1] = 9
###print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Copying array**

In [ ]:
arr2 = np.array([1,2,3])
brr = arr2
##print(brr)
brr[0] =  100
print(brr)
print(arr2,"arr2") # you are not copying but assigning arrays

[100   2   3]
[100   2   3] arr2


**Mathematics**

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a /2)

[3 4 5 6 7 8]
[-1  0  1  2  3  4]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]


In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

**Linear Algebra**

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])

In [ ]:

np.min(stats)

np.int64(1)

In [ ]:
np.max(stats,axis = 0)

array([4, 5, 6])

In [ ]:
np.sum(stats)

np.int64(21)

**Reorganizing arrays**

In [ ]:
bef = np.array([[1,2,3,4],[5,6,7,8]])
print(bef)
af = bef.reshape((2,2,2))
print(af)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#vertical staacking
c1 = np.array([1,2,3,4])
c2 = np.array([5,6,7,8])
np.vstack([c1,c2,c2,c1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
h1 = np.ones((2,2)) #hortizantal stackng
h2 = np.zeros((2,3))
np.hstack([h1,h2])


array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [ ]:
sample = np.genfromtxt('/content/sample.txt',delimiter=',')
sample = sample.astype('int32')
print(sample)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


**Indexing**

In [ ]:
sample[sample > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
(~(sample > 50) & (sample < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])